### ISSUE TITLE
Bug: Can't load ESM module in Node.js

### ISSUE THREAD

**Issue by nzakas** [Antonio-Laguna/markdown-it-image-figures#10]
## Environment:

* Node v16.3.0
* npm v7.10.0

## What I did

Tried to load the plugin in an ESM file like this:

```js
import figuresPlugin from "markdown-it-image-figures";
```

## What happened

Got the following error:

```
import figuresPlugin from "markdown-it-image-figures";
       ^^^^^^^^^^^^^
SyntaxError: The requested module 'markdown-it-image-figures' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:121:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:171:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

## Notes

From looking through the `dist` folder locally, it appears that all of the generated files that should be ESM are actually CommonJS, including the ones marked as `.module.js` and `.mjs`. I'm guessing this has something to do with microbundle.

**Comment by Antonio-Laguna** [comment]
@nzakas thanks for opening this! I've tracked down the issue and I'm releasing a fix ASAP. Also created tests to ensure that the module is correctly exported on all forms.

**Comment by Antonio-Laguna** [comment]
Has been released as 2.0.2, @nzakas could you double-check on your end?

**Comment by nzakas** [comment]
Confirmed! This fixes the issue. Thanks so much.

**Comment by Antonio-Laguna** [comment]
Thanks for confirming! Closing this!
