### ISSUE TITLE
Request: Use alt as figcaption

### ISSUE THREAD

**Issue by nzakas** [Antonio-Laguna/markdown-it-image-figures#11]
I'm trying to mimic the behavior of images in [Markua](https://leanpub.com/markua/read#images), where the `alt` attribute doubles as the value of `figcaption`. Would you consider changing the `figcaption` option to support this? Here's what I have in mind:

* `figcaption: true` - same as today, use the title as `figcaption`
* `figcaption: "title"` - equivalent of `figcaption: true`
* `figcaption: "alt"` - use the `alt` attribute as `figcaption`

If you're open to it, I can send a pull request.

**Comment by Antonio-Laguna** [comment]
@nzakas that sounds like a reasonable behavior! Completely open to it

**Comment by nzakas** [comment]
Awesome, thanks. I'll put together a PR to see what you think!
