### ISSUE TITLE
Width and height attributes

### ISSUE THREAD

**Issue by tonqa** [Antonio-Laguna/markdown-it-image-figures#14]
Browsers nowadays need the width and height attributes in order to reserve space for the images to render.

Please add width and height attributes to the markdown syntax like suggested [here in Github](https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown).

Your implementation is neat and awesome, please make it even better!

**Comment by Antonio-Laguna** [comment]
@tonqa I'll think about this! Thanks for opening this issue!

**Comment by Antonio-Laguna** [comment]
@tonqa this went a lot of time without any attention. I'm sorry about that. I can see it is supported with `markdown-it-attrs` correctly:

This input:

```md
![alt](fig.png){width=100 height=200}
```

Generates the following:

```html
<figure><img src="fig.png" alt="alt" width="100" height="200"></figure>
```

Which is what you would expect.

Let me know if you need anything else here! Thanks for your patience.
