### ISSUE TITLE
Conflict with markdown-it-footnote

### ISSUE THREAD

**Issue by eaton** [Antonio-Laguna/markdown-it-image-figures#2]
Hello!

Great project; yours is the only one that takes advantage of `title` text for the figcaption rather than repurposing alt text. Very happy with the results! The only downside is that it seems to collide with the popular `markdown-it-footnotes` plugin. When When only `markdown-it-image-figures` is installed, everything is good. When only `markdown-it-footnotes` is installed, everything's good.

However, when both are installed on a vanilla Eleventy blog, the following markdown text:

```
Lorem ipsum dolor sit amet.[^1]
[^1]: Here is the footnote. 

![Kitten alt text](https://placekitten.com/g/500/300 "Kitten title text")
```

…results in the following error:

```
[eleventy:dev] `TemplateContentRenderError` was thrown
[eleventy:dev] > Cannot read property 'footnotes' of undefined
[eleventy:dev] 
[eleventy:dev] `TemplateContentRenderError` was thrown
[eleventy:dev] > Cannot read property 'footnotes' of undefined
[eleventy:dev] 
[eleventy:dev] `TypeError` was thrown:
[eleventy:dev]     TypeError: Cannot read property 'footnotes' of undefined
[eleventy:dev]         at Array.footnote_ref (/Users/jeff/work/autogram/home/node_modules/markdown-it-footnote/index.js:239:20)
[eleventy:dev]         at ParserInline.tokenize (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/parser_inline.js:135:22)
[eleventy:dev]         at ParserInline.parse (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/parser_inline.js:163:8)
[eleventy:dev]         at Array.inline (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
[eleventy:dev]         at Core.process (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/parser_core.js:51:13)
[eleventy:dev]         at MarkdownIt.parseInline (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/index.js:560:13)
[eleventy:dev]         at Array.<anonymous> (/Users/jeff/work/autogram/home/node_modules/markdown-it-image-figures/dist/markdown-it-images-figures.js:1:1229)
[eleventy:dev]         at Core.process (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/parser_core.js:51:13)
[eleventy:dev]         at MarkdownIt.parse (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/index.js:523:13)
[eleventy:dev]         at MarkdownIt.render (/Users/jeff/work/autogram/home/node_modules/markdown-it/lib/index.js:543:36)
```

There seems to be no problem when using the [Implicit Figures](https://github.com/arve0/markdown-it-implicit-figures) plugin, though obviously it pulls from the alt tag instead of the title.

**Comment by eaton** [comment]
A side note — the issue only triggers when the `figcaption` option is set to `true`; removing it from the config object, explicitly setting it to `false`, or using the plugin's default options doesn't trigger the error.

In addition, if the title text is removed from the markdown string, the error doesn't occur, even if the `figcaption` option remains enabled.

**Comment by Antonio-Laguna** [comment]
Hi @eaton ! Thanks for reporting this. I'll take a look soon and try to reproduce the error and check where the issue could be!

**Comment by Antonio-Laguna** [comment]
Hey @eaton I couldn't get this to have a test that fails right now. Here's the assert I've prepared: 

```js
md = mdIT().use(implicitFigures).use(footNotes);
const src = `Lorem ipsum dolor sit amet.[^1]
[^1]: Here is the footnote.

![Kitten alt text](https://placekitten.com/g/500/300 "Kitten title text")`;
```

And the output is: 

```html
<p>Lorem ipsum dolor sit amet.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p>
<figure><img src="https://placekitten.com/g/500/300" alt="Kitten alt text" title="Kitten title text"></figure>
<hr class="footnotes-sep">
<section class="footnotes">
<ol class="footnotes-list">
<li id="fn1" class="footnote-item"><p>Here is the footnote. <a href="#fnref1" class="footnote-backref">↩︎</a></p>
</li>
</ol>
</section>
```

This doesn't really crash and the output seems OK to me. Could you isolate the issue you're experiencing so I can try and fix this?

**Comment by Antonio-Laguna** [comment]
Due to inactivity I've closed this. Let me know if this still happens and I can take a look.

**Comment by Antonio-Laguna** [comment]
I've managed to track the issue right now. Pushing a fix
