### ISSUE TITLE
image api

### ISSUE THREAD

**Issue by Tokyodays** [Antonio-Laguna/markdown-it-image-figures#3]
hello.

i need a favor to ask you.
I want you to support image api

* md
`[title](url {fm:jpg,w:300,h:400})`

* render
`<img src="url?fm=jpg&w=300&h=400">`

thank you

**Comment by Antonio-Laguna** [comment]
Hello!

I'm not sure what's the point in this when you can just adapt the URL to be like the final one rather than adding external attributes like that.

**Comment by Tokyodays** [comment]
i fixed this probrem.

`[title](url?fm=jpg&w=300&h=400)`

that is ok.

thank you.
