### ISSUE TITLE
Use in the browser

### ISSUE THREAD

**Issue by KoljaL** [Antonio-Laguna/markdown-it-image-figures#5]
Hi Antonio,

Is there a possibility to use your plugin directly in the browser, without NPM?
With many other * markdown-it * plugins, this is over
    `<script defer src="/markdown-it-plugin.js"></script>`
and
    `md.use(window.markdownitPlugin, 'options');`
possible.

Thank you for your work :-)

**Comment by Antonio-Laguna** [comment]
Hi @KoljaL can you show me one example? I haven't thought about that but I can check what it would entail

**Comment by KoljaL** [comment]
Like the footnote plugin: https://github.com/markdown-it/markdown-it-footnote#use  
The browser has to load the file `dist/markdown-it-footnote.js`
