### ISSUE TITLE
Allow native lazy loading without removing `src` attribute

### ISSUE THREAD

**Issue by paulrobertlloyd** [Antonio-Laguna/markdown-it-image-figures#7]
Thanks for creating this plugin - solves one of the longstanding issues with Markdown and its lack of support for `figure`, in a really clever and sensible way! However, I’ve come across one issue.

Currently this plugin has a `lazy` attribute. Adding this does 3 separate things:

* Adds a `loading="lazy"` attribute to the image
* Adds a class attribute. The default value is `lazy`, otherwise uses string value given for the `lazy` option
* Replaces `src` with a `data-src` attribute

This allows authors to use lazy loading scripts, which typically replace `data-src` with `src` at the point at which an image needs to be loaded.

However, this lazy loading is increasingly being [added to browsers natively](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading). It may be desirable therefore to want to enable lazy loading **but not** replace the `src` attribute or add any classes.

## Proposed (breaking) change

Instead of several values changing based on the value given for `lazy`, instead provide a set of explicit options:

* Change the behaviour of the `lazy` option. Make it a boolean, and only output `loading="lazy"` if `true`.
* Add another boolean option, perhaps `removeSrc`. If `true`, replace `src` attribute with `data-src`.
* Add another option, perhaps `classes`. If given, `classes` attribute is added with the given value.

### Default behaviour `{ lazy: false, removeSrc: false, classes: false }`:

  ```html
    <figure>
      <img alt="alt" src="fig.png">
    </figure>
  ```

### To replicate the existing behaviour of v1.2.0 `{ lazy: true, removeSrc: true, classes: 'lazy' }`:
  
  ```html
    <figure>
      <img alt="alt" data-src="fig.png" class="lazy" loading="lazy">
    </figure>
  ```

### To use native lazy loading: `{ lazy: true }`:

  ```html
    <figure>
      <img alt="alt" src="fig.png" loading="lazy">
    </figure>
  ```

There might be better ways of achieving the above of course, open to suggestions!

**Comment by Antonio-Laguna** [comment]
@paulrobertlloyd thanks a lot for this thoughtful issue. I think you're completely right. I created this as a fork to solve issues the original package had and didn't think too much at that point in time :P 

I think this makes sense to move forward just as you suggested and I'll give it a go probably this week so, stay tuned!

**Comment by Antonio-Laguna** [comment]
@paulrobertlloyd this has been now released here: https://github.com/Antonio-Laguna/markdown-it-image-figures/releases/tag/2.0.0 !

Again thanks, was a great suggestion.

**Comment by paulrobertlloyd** [comment]
Brilliant – thanks for the fix and quick turnaround @Antonio-Laguna!
